# permissions for end users to view fatejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fatejob-viewer-role
rules:
- apiGroups:
  - webapp.kubefate.net
  resources:
  - fatejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.kubefate.net
  resources:
  - fatejobs/status
  verbs:
  - get
